vm_name                 = "test-vm"
vm_size                 = "Standard_DS1_v2"
vnet_name               = "test-vnet"
subnet_name             = "test-subnet"
location                = "Central US"
vnet_address_space      = ["10.0.0.0/16"]
subnet_address_prefixes = ["10.0.2.0/24"]
nic_name                = "test-nic"
resource_group_name     = "test-rg"
